name: Build App

on:
 push:
 pull_request:

env:
  DAY_OF_WEEK: Monday
  ACT_CACHE: "actions/cache@v3"

jobs:
  build:
    permissions:
      actions: read  # get run data
      #checks: write
      contents: read  # do checkout
      # deployments: write
      # id-token: write
      # issues: write
      # discussions: write
      # packages: write
      # pages: write
      # repository-projects: write
      # statuses: write

    runs-on: windows-latest

    steps:
    
    - name: Print
      run: env | sort

    - name: checkout
      uses: actions/checkout@v3

    - name: Upload the artifcat file
      uses: actions/upload-artifact@v4
      with: 
        name: original-artifact
        path: "./files/Multifiles/Folder_Zip_DLL.zip"


    - name: Run submit signing request for FQA ORG1
      id: "submit_with_download_org1"
      uses: SignPath/github-actions/actions/submit-signing-request@feature/SIGN-6727
      with:
        #connector-url: 'https://githubactions.connectors.fqa.test.signpath.io:15021/'
        connector-url: 'https://7fk0b9xm-44353.euw.devtunnels.ms/' 
        #connector-url: 'https://webhook.site/f9af1302-0dc3-48f0-95b8-31fd2e43679b/' 
        api-token: '${{ secrets.SIGN_PATH_API_TOKEN_FQA_ORG1 }}'
        organization-id: '54145c58-966f-4f56-83c3-4fda3f27da37'
        project-slug: 'GithubTestOrg1'
        # this SigningPolicy has auto-approve enabled, so you don't need to approve the signing request
        signing-policy-slug: 'GithubTestSp'
        artifact-configuration-slug: 'archive'
        github-artifact-name: original-artifact
        #github-token: '${{ secrets.GHA_TOKEN }}'
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        wait-for-completion: true
        output-artifact-directory: 'org1/content'

    - uses: actions/download-artifact@v4
      with:
        name: original-artifact
        path: org1/content2

    # - name: Sleep for 30 seconds
    #   run: Start-Sleep -s 300
    #   shell: powershell

    - uses: actions/upload-artifact@v3
      with: 
        name: Org1SignedArtifact
        path: "org1"


    - name: Log submit-signing-request task output for Org1
      run: |
           echo "signing-request-id [${{steps.submit_with_download_org1.outputs.signing-request-id }}]"
           echo "signing-request-web-url [${{steps.submit_with_download_org1.outputs.signing-request-web-url }}]"
           echo "signpath-api-url [${{steps.submit_with_download_org1.outputs.signpath-api-url }}]"
           echo "signed-artifact-download-url [${{steps.submit_with_download_org1.outputs.signed-artifact-download-url }}]"
