name: Build App

on:
 push:
 pull_request:

jobs:

  build:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      pages: write
      repository-projects: write
      statuses: write

   # runs-on: X64

    steps:
    - name: Print
      run: env | sort

  
